---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web2
  namespace: argocd
  labels:
    name: web2
spec:
  project: default
  source:
    repoURL: https://github.com/cuonghv00/argocd-app-config.git
    targetRevision: HEAD
    path: app2
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
